spring.application.name=easypadel-backend

# Base de dades
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/easy_padel}
spring.datasource.username=${DB_USER:jjaavi}
spring.datasource.password=${DB_PASSWORD:123456}

# L'esquema el gestiona bd/bd.sql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Nombre de dies maxim amb antelacio per fer una reserva
app.reserves.dies-maxim-antelacio=10
